### ISSUE TITLE
Add Seq.flatMap() overload

### ISSUE THREAD

**Issue by sargue** [jOOQ/jOOL#228] opened 2016-04-21 13:54 UTC
I've found myself repeating this pattern quite a lot.

```java
class Topic {
   List<String> labels() { ... }
}

List<Topic> topics = ...;

List<String> allLabels = Seq.seq(topics).flatMap(topic -> topic.labels().stream()).distinct().toList();
```

Should we add `Seq.flatMap()` methods overloaded for every container from which we can create a stream() ?

So, the above will become:

```java
List<String> allLabels = Seq.seq(topics).flatMap(Topic::labels).distinct().toList();
```

What do you think?

**Comment by lukaseder** [comment] 2016-04-21 16:13
The problem is that `flatMap(Function<? extends Seq<T>>)` cannot be overloaded with other `Function` arguments due to generic type erasure. What might be possible is to create dedicated `@FunctionalInterface` types for each one of those containers, and then overload by those. I'll evaluate if that's doable and if nothing breaks at the call site by adding such overloads - I'm a bit wary of adding overloads that take lambda expressions, it's probably a bad idea. Details here:
https://blog.jooq.org/2015/01/29/you-will-regret-applying-overloading-with-lambdas/

**Comment by sargue** [comment] 2016-04-22 06:12
I see. Yes, I rememeber reading your post, you're right.

Then maybe we should consider the most useful ones and use different method names. Like `flatMapIterable` and so on. Maybe just that one, all of them or **none of them**. I'll let the hard design decisions up to you. ;-)

Thanks!

**Comment by lukaseder** [comment] 2016-04-22 06:25
Huh, yeah, but `flatMapIterable()`... is that really easier than `flatMap(t -> seq(t))` ? :)

**Comment by sargue** [comment] 2016-04-22 07:03
No, not really.

**Comment by lukaseder** [comment] 2016-04-22 07:09
OK, I'll close this for now. I do agree with the intent. I've run across this myself numerous times too. And it would be consistent with much of the existing API, which also overloads on `Stream`, `Seq`, `Iterable`, `Iterator`, `T...`, etc.

But unfortunately, due to the lack of generic type reification (or union types) in the Java language, this particular case shouldn't be implemented.

**Closed by lukaseder** 2016-04-22 07:09 UTC
Labels: P: Medium, T: Enhancement
