### ISSUE TITLE
Have Seq.seq(Map) provide a mapValues

### ISSUE THREAD

**Issue by stephenh** [jOOQ/jOOL#257] opened 2016-08-24 18:36 UTC
Mapping values is a very common operation; right now it requires:

```
    Map<Long, Long> m = new HashMap<>();
    m.put(1L, 2L);
    Map<Long, Long> m2 = Seq.toMap(Seq.seq(m).map(e -> Tuple.tuple(e.v1, e.v2 * 2)));
```

In theory I'd like to do:

```
    Map<Long, Long> m2 = seq(m).mapValues(v -> v * 2);
```

If the `Seq.seq(Map)` method returned some sort of `MapSeq` subclass of `Seq`, it could provide Map/tuple-aware methods like `mapValues`.

**Comment by stephenh** [comment] 2016-08-24 18:39
I guess technically `mapValues` would probably result a `Seq<Tuple<K, V>>` or `MapSeq<K, V>`, which means `mapValues` in my example might need another `toMap` (which granted is already taken) to get it back to a Map type:

```
    Map<Long, Long> m2 = seq(m).mapValues(v -> v * 2).toMap();
```

**Comment by stephenh** [comment] 2016-08-24 18:42
A coworker pointed out I'm abusing Seq when I really have a map, so probably want something like:

https://github.com/javaslang/javaslang/blob/master/javaslang/src/main/java/javaslang/collection/Map.java#L183

**Comment by bendem** [comment] 2016-08-24 20:57
So basically `Map#replaceAll(BiFunction)`? 
```java
map.replaceAll((k, v) -> v * 2);
```

**Comment by stephenh** [comment] 2016-08-24 21:15
Haha, yes! Today I learned. :-)

That said, I still wouldn't mind a Seq.mapValues-style way of doing it.

**Comment by lukaseder** [comment] 2016-08-25 09:50
Note, there's `Tuple2.map2()` which might be a bit more useful in your case, although I absolutely agree with @bendem that a `replaceAll()` call is optimal in this particular situation.

I'm not sure if a new `MapSeq` type would do the trick. I feel that it is too specific to be really useful. I much prefer a `Seq2` type as suggested here: https://github.com/jOOQ/jOOL/pull/172. The only difference being that a `MapSeq` would have unique keys. With `Seq2`, your `mapValues()` method would simply become a `map2()` method, or a `map((k, v) ->tuple(k, v * 2))` call.

Unfortunately, both `MapSeq` and `Seq2` are not trivial to introduce into the type system in a backwards-compatible way, but with the additional use-case in mind, I will think that `Seq2` will really add value to jOOλ. I'm closing this issue as a duplicate of #172

**Closed by lukaseder** 2016-08-25 09:50 UTC
Labels: P: Medium, T: Enhancement
