### ISSUE TITLE
filter and cast 

### ISSUE THREAD

**Issue by pgrisafi** [jOOQ/jOOL#246] opened 2016-08-15 14:00 UTC
On thing I reaaaaaally miss from Guava was the filter-and-cast in FluentIterable. You know, the
```
List<String> strings = FluentIterable.from(objects)
        .filter(String.class)
        .toList();
```
In java8 you need an extra map function I find annoying

```
    List<String> strings = objects
            .stream()
            .filter(p -> p instanceof String)
            .map(p -> (String) p)
            .collect(Collectors.toList());
```
It would be nice to be able to do
```
    List<String> strings = Seq.seq(objects)
            .filter(String.class)
            .toList();
```
Again, thanks for this beautiful lib!

**Comment by lukaseder** [comment] 2016-08-15 19:43
Duplicate of https://github.com/jOOQ/jOOL/issues/56. We call it `Seq<T>.ofType(Class<U>)`. The naming was borrowed from .NET's LINQ, which knows `OfType()` and `Cast()` operations.

**Closed by lukaseder** 2016-08-15 19:43 UTC
Labels: P: Medium, R: Duplicate, T: Enhancement

**Comment by pgrisafi** [comment] 2016-08-16 14:07
You are right, and it's even in the readme.md
Sorry
May I suggest a 
`@see #ofType(Class) if you want to filter and cast `
in the filter documentation? the name 'ofType' is not natural if you don't know or remember .net framework

**Comment by lukaseder** [comment] 2016-08-16 16:09
Sure, that makes sense. Done
