### ISSUE TITLE
Grouped and groupBy gives different results when you sort by Enum field.

### ISSUE THREAD

**Issue by NikitaPanteleev** [jOOQ/jOOL#325] opened 2018-02-14 14:12 UTC
### Expected behavior and actual behavior:
https://stackoverflow.com/questions/48787686/org-jooq-lambda-seq-different-behaviour-of-grouped-and-groupby-functions

Grouped and groupBy gives different results when you use them with java Enum field. I created collection from 4 elements and I expect them to be grouped into 2 groups

### Steps to reproduce the problem:
```
import org.jooq.lambda.Seq;
import org.jooq.lambda.tuple.Tuple2;
import java.util.Arrays;
import java.util.List;
import java.util.Map;

public class Application {
  public static void main(String[] args) {
    List<Foo> foos = Arrays.asList(
        new Foo().setStatus(StatusInfo.ORDER_PLACED).setOrderNo(1L),
        new Foo().setStatus(StatusInfo.ORDER_PLACED).setOrderNo(2L),
        new Foo().setStatus(StatusInfo.ORDER_PLACED).setOrderNo(3L),
        new Foo().setStatus(StatusInfo.ORDER_CANCELLED).setOrderNo(4L)
    );
    List<Tuple2<String, Seq<Foo>>> list1 = Seq.seq(foos)
        .grouped(foo -> {
          System.out.println("Foo1: " + foo + " - " + foo.getStatus().toString());
          return foo.getStatus().toString();
        }).toList();

    Map<String, List<Foo>> list2 = Seq.seq(foos).groupBy(foo -> {
      System.out.println("Foo2: " + foo);
      return foo.getStatus().toString();
    });

    System.out.println("Foos size: " + foos.size());
    System.out.println("Size 1: " + list1.size());
    System.out.println("Size 2: " + list2.keySet().size());
  }

  static class Foo {
    StatusInfo status;
    Long orderNo;

    public StatusInfo getStatus() {
      return status;
    }

    public Foo setStatus(StatusInfo status) {
      this.status = status;
      return this;
    }

    public Long getOrderNo() {
      return orderNo;
    }

    public Foo setOrderNo(Long orderNo) {
      this.orderNo = orderNo;
      return this;
    }
  }

  public enum StatusInfo {
    ORDER_PLACED, ORDER_CANCELLED;
  }
}
```

Output:
```
Foo1: Application$Foo@57ad2aa7 - ORDER_PLACED
Foo1: Application$Foo@5b3f61ff - ORDER_PLACED
Foo1: Application$Foo@1ef6d34c - ORDER_PLACED
Foo2: Application$Foo@57ad2aa7
Foo2: Application$Foo@5b3f61ff
Foo2: Application$Foo@1ef6d34c
Foo2: Application$Foo@6fa34d52
Foos size: 4
Size 1: 1
Size 2: 2
```
Sizes of both List and keySet should be the same, but it looks like the last element is skipped in the first method.
### Versions:

- jOOλ: 0.9.12
- Java: 1.8

**Comment by NikitaPanteleev** [comment] 2018-02-14 15:47
Might be duplicated of https://github.com/jOOQ/jOOL/issues/271

Is there any solution for current release?

**Comment by NikitaPanteleev** [comment] 2018-02-18 12:56
Not sure that library is still maintained. So, for now, I build the latest master: https://bintray.com/nikitapanteleev/jOOL/jOOL/0.9.13

And in future, I will switch to another library.

**Comment by lukaseder** [comment] 2018-02-19 08:51
Thank you so much for your patience @NikitaPanteleev. This library is maintained, yes. Indeed, release 0.9.13 is overdue. I'm sorry for the inconvenience.

I'll look into whether this is a duplicate, soon.

**Comment by lukaseder** [comment] 2018-02-28 12:15
Thanks again for your patience. I can confirm this seems to be a duplicate of #271. I'll close this and proceed with releasing 0.9.13 today.

**Closed by lukaseder** 2018-02-28 12:15 UTC
Labels: P: Medium, T: Defect
