### ISSUE TITLE
consider adding mapWithIndex

### ISSUE THREAD

**Issue by pgrisafi** [jOOQ/jOOL#316] opened 2017-06-15 12:04 UTC
Minor enhancement: I've noted that in many cases having the index while you map is useful, specially when you need to log, or handle errors.

My pattern now is writing something like 
```java
    Seq.seq(list)
    .zipWithIndex()
    .map(elementAndIndex -> doSomethingWith(elementAndIndex.v1, elementAndIndex.v2))
    .whatever 
```
but then, it is kind of annoying. I think it would be better to write
```java
    Seq.seq(list)
    .mapWithIndex(element, index -> doSomethingWith(element, index))
    .whatever 
```

It is just one line of code, be it enhances readability since not everyone is familiar with zip functions, and you got to use more meaningful variable names since you are not using a tuple.

(maybe there is already a function like that and couldn't find it?)

Thanks again for this little gem!

**Comment by lukaseder** [comment] 2017-06-19 18:01
Thank you very much for your suggestion. Just to be sure, you mean for `mapWithIndex` to take a single `BiFunction` argument:

```java
mapWithIndex((element, index) -> doSomethingWith(element, index))
```

Am I right? Because that's already implemented: https://github.com/jOOQ/jOOL/pull/262.

I'm closing this as a duplicate of #262. Feel free to reopen if I misunderstood.

**Closed by lukaseder** 2017-06-19 18:01 UTC
Labels: P: Medium, T: Enhancement

**Comment by pgrisafi** [comment] 2017-06-21 12:18
Agg, my bad. Thanks again
